In [1]:
class Model():
    def __init__(self, coefficients, intercept):
        self.coefficients = coefficients
        self.intercept = intercept
    def predict(self, X):
        return X.dot(self.coefficients) + self.intercept

In [60]:
SalaryPredictor = Model(coefficients=[3.815718562111416,2.32091090376625,-0.034417153618212605,3.895412777294307,-1.1985643975295406  ], intercept=10.043764045550192)

In [61]:
import pandas as pd
import numpy
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

In [62]:
current_season_df = pd.read_csv("current stats and salaries.csv")

In [63]:
features = ['PTS', 'TOV', 'AST', 'VORP', 'PER']
X = current_season_df[features]
scaler = StandardScaler()
X_standardized = scaler.fit_transform(X)

In [64]:
predictions = (SalaryPredictor.predict(X_standardized)*1000000).astype(int)

In [65]:
current_season_df['Prediction'] = predictions

In [66]:
display_df = current_season_df[['Player','Salary','Prediction']]

In [88]:
display_df.sort_values(by='Prediction', ascending=False).head(30)

                      Player    Salary  Prediction
2               Nikola Jokic  47607350    49915150
17               Luka Doncic  40064220    48368379
8      Giannis Antetokounmpo  45640084    44459773
4                Joel Embiid  47607350    44291796
33   Shai Gilgeous-Alexander  33386850    43743505
1               Kevin Durant  47649433    36836348
34          Donovan Mitchell  33162030    35619907
15                Trae Young  40064220    35575164
3               LeBron James  47607350    35318138
0              Stephen Curry  51915615    34611056
42          Domantas Sabonis  30600000    34500453
35              Jayson Tatum  32600060    34154113
50             Jalen Brunson  26346666    33808312
108          Anthony Edwards  13534817    32783673
199        Tyrese Haliburton   5808435    32177869
14             Anthony Davis  40600080    31422798
6              Kawhi Leonard  45640084    31076958
257           Alperen Sengun   3536280    30796563
24              Devin Booker  36016200    30051363
164           Scottie Barnes   8008680    29502856
23        Karl-Anthony Towns  36016200    29252933
46             Julius Randle  28226880    29067021
250             Desmond Bane   3845083    28320056
27              James Harden  35680595    27773878
37              De'Aaron Fox  32600060    27771731
9             Damian Lillard  45640084    27654201
233             Tyrese Maxey   4343920    27519183
123           Paolo Banchero  11608080    26959526
131              LaMelo Ball  10900635    26850660
115        Victor Wembanyama  12160632    26401451

In [87]:
display_df[display_df['Player'].isin(['Victor Wembanyama', 'Chet Holmgren'])]

                Player    Salary  Prediction
115  Victor Wembanyama  12160632    26401451
138      Chet Holmgren  10386000    23950300